# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Latin Dancing Edinburgh
email: your-email@domain.com
author: Matyas K. Zsoldos
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2022 Matyas K. Zsoldos, All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: meetup
    url: https://www.meetup.com/edinburgh-latin-dance-salsa-and-bachata-meetup/
  - title: facebook
    url: https://www.facebook.com/Bachata-Latin-Dance-Edinburgh-381505722015864
  - title: linkedin
    url: 
