# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Latin Dancing Edinburgh
email: your-email@domain.com
author: Matyas K. Zsoldos
description: > # "Write an awesome description for your new site here. 
  We organise weekly events, out of love for dancing and music: FREE Salsa, Bachata, Merengue & Reggaeton Lessons held in either OUTDOORS Park in summer, MIRRORED STUDIOS in winter.
copyright: 'Copyright &copy; 2022 Matyas K. Zsoldos, All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: events
    url: https://www.meetup.com/edinburgh-latin-dance-salsa-and-bachata-meetup/
  - title: facebook
    url: https://www.facebook.com/Bachata-Latin-Dance-Edinburgh-381505722015864

